name: Text summarization Okareo flow
env:
  SKIP_YARN_COREPACK_CHECK: true
  DEMO_BUILD_ID: ${{ github.run_number }}
  OKAREO_API_KEY: ${{ secrets.OKAREO_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  summarization:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Okareo
        run: |
          curl -O -L https://github.com/okareo-ai/okareo-cli/releases/download/v0.0.13/okareo_0.0.13_linux_386.tar.gz
          export OKAREO_PATH="~/development/okareo"
          export PATH="$PATH:$OKAREO_PATH/bin"
          okareo -v
      
      - name: Text Summarization Evaluation
        run: |

          okareo -v
          okareo run -f text_summarization